extends:
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 6
rules:
  # Possible Errors
  no-console: error
  no-extra-parens: 0

  # Best Practices
  array-callback-return: error
  block-scoped-var: error
  complexity:
    - warn
    - 20
  consistent-return: error
  no-alert: warn
  no-caller: error
  no-else-return: error
  no-empty-function: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-implicit-coercion: warn
  no-implied-eval: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-multi-spaces: error
  no-multi-str: error
  no-native-reassign: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: warn
  no-proto: error
  no-restricted-properties: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: warn
  no-useless-return: error
  no-void: error
  wrap-iife: error
  yoda:
    - error
    - never

  # Strict Mode
  strict:
    - error
    - global

  # Variables
  no-delete-var: error
  no-label-var: error
  no-shadow: error
  no-undef-init: error
  no-undefined: error
  no-use-before-define: error

  # Node.js
  callback-return: error
  global-require: warn
  no-mixed-requires: warn
  no-new-require: error
  no-path-concat: error
  no-process-exit: error

  # Stylistic Issues
  array-bracket-newline: error
  array-bracket-spacing: error
  array-element-newline: error
  block-spacing: error
  brace-style: error
  camelcase: warn
  capitalized-comments: warn
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  func-call-spacing: error
  function-paren-newline: error
  indent: [off, 2, {
    SwitchCase: 1
    }]
  key-spacing: error
  keyword-spacing: error
  line-comment-position: warn
  lines-around-comment: warn
  max-depth: warn
  max-len: [warn, {
    code: 120,
    tabWidth: 2,
    ignoreComments: true,
    ignoreUrls: true
    }]
  max-nested-callbacks: error
  max-statements-per-line: warn
  multiline-comment-style: error
  new-parens: error
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-inline-comments: warn
  no-lonely-if: error
  no-mixed-operators: error
  no-mixed-spaces-and-tabs: error
  no-multi-assign: error
  no-multiple-empty-lines: error
  no-nested-ternary: error
  no-new-object: error
  no-plusplus: error
  no-spaced-func: error
  no-trailing-spaces: warn
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-spacing: error
  one-var:
    - error
    - never
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment: warn
  operator-linebreak:
    - error
    - after
  padded-blocks: error
  quotes: error
  semi: error
  semi-spacing: error
  space-before-blocks: warn
  space-in-parens: warn
  space-infix-ops: error
  space-unary-ops: [error, {
    words: true,
    nonwords: false,
    overrides: {
      typeof: false
      }
    }]
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error

  # ECMAScript 6
  arrow-body-style: error
  arrow-spacing: error
  no-confusing-arrow: error
  no-duplicate-imports: error
  no-var: error
  prefer-const: warn
