image: ubuntu
platform: Any CPU

environment:
  CODACY_PROJECT_TOKEN:
    secure: N7WXAKLOSieULD0oBokiOpy2Dq+wuiderT/xOa2k4McBCXQaSNdNMZDsDIChGZbZ
  CC_TEST_REPORTER_ID:
    secure: ApLPZyCJbm+8kVZt1DZZVAUyXq/Q1npwImEqzWwqFd4COg6Ecx1cAL0KJBo34Rh51mDV9keHBu+TzmeAMZ01/KzZBAvwmdF8YHImqJPy4VA=
  CYPRESS_RECORD_KEY:
    secure: Rp/+P91xPqWssFtI5B5m4lPnDMjdfPbGpYxXvsiSy9Uym5WGZcWIUL3sdLjz59PU

stack: "node 14"

cache:
  - node_modules      # local npm modules
  - $HOME/.cache      # Cypress
  - $HOME/.npm        # NPM

install:
  - sh: npm install -g npm@7
  # Output useful info for debugging.
  - node --version
  - npm --version
  # install modules
  - sh: npm ci
  - sh: npm install -g mocha c8 cypress

before_test:
  # Download codeclimate test report
  - sh: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate-test-reporter
  - sh: chmod +x ./codeclimate-test-reporter

test_script:
  - cp ./data/configAppveyor.js ./data/config.js
  - c8 --reporter=lcov --reporter=text --reporter=text-summary mocha --timeout 30000

after_test:
  # Send test result to codeclimate
  - sh: ./codeclimate-test-reporter before-build
  - sh: ./codeclimate-test-reporter after-build -t lcov --exit-code $?
  # Send test result to Codacy
  - sh: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info

artifacts:
  - path: cypress\videos\**\*.mp4
    name: Cypress Videos

# Don't actually build.
build: off
