"use strict";
const express_1 = require("express");
const handler_userManagement = require("../handlers/admin-get/userManagement");
const handler_doCreateUser = require("../handlers/admin-post/doCreateUser");
const handler_doUpdateUser = require("../handlers/admin-post/doUpdateUser");
const handler_doGetUserProperties = require("../handlers/admin-post/doGetUserProperties");
const handler_doUpdateUserProperty = require("../handlers/admin-post/doUpdateUserProperty");
const handler_doResetPassword = require("../handlers/admin-post/doResetPassword");
const handler_doDeleteUser = require("../handlers/admin-post/doDeleteUser");
const handler_cleanup = require("../handlers/admin-get/cleanup");
const handler_doCleanupTable = require("../handlers/admin-post/doCleanupTable");
const handler_offences = require("../handlers/admin-get/offences");
const handler_doAddOffence = require("../handlers/admin-post/doAddOffence");
const handler_doUpdateOffence = require("../handlers/admin-post/doUpdateOffence");
const handler_doDeleteOffence = require("../handlers/admin-post/doDeleteOffence");
const handler_locations = require("../handlers/admin-get/locations");
const handler_doAddLocation = require("../handlers/admin-post/doAddLocation");
const handler_doUpdateLocation = require("../handlers/admin-post/doUpdateLocation");
const handler_doDeleteLocation = require("../handlers/admin-post/doDeleteLocation");
const handler_bylaws = require("../handlers/admin-get/bylaws");
const handler_doAddBylaw = require("../handlers/admin-post/doAddBylaw");
const handler_doUpdateBylaw = require("../handlers/admin-post/doUpdateBylaw");
const handler_doUpdateOffencesByBylaw = require("../handlers/admin-post/doUpdateOffencesByBylaw");
const handler_doDeleteBylaw = require("../handlers/admin-post/doDeleteBylaw");
const router = express_1.Router();
router.get("/userManagement", handler_userManagement.handler);
router.post("/doCreateUser", handler_doCreateUser.handler);
router.post("/doUpdateUser", handler_doUpdateUser.handler);
router.post("/doUpdateUserProperty", handler_doUpdateUserProperty.handler);
router.post("/doResetPassword", handler_doResetPassword.handler);
router.post("/doGetUserProperties", handler_doGetUserProperties.handler);
router.post("/doDeleteUser", handler_doDeleteUser.handler);
router.get("/cleanup", handler_cleanup.handler);
router.post("/doCleanupTable", handler_doCleanupTable.handler);
router.get("/offences", handler_offences.handler);
router.post("/doAddOffence", handler_doAddOffence.handler);
router.post("/doUpdateOffence", handler_doUpdateOffence.handler);
router.post("/doDeleteOffence", handler_doDeleteOffence.handler);
router.get("/locations", handler_locations.handler);
router.post("/doAddLocation", handler_doAddLocation.handler);
router.post("/doUpdateLocation", handler_doUpdateLocation.handler);
router.post("/doDeleteLocation", handler_doDeleteLocation.handler);
router.get("/bylaws", handler_bylaws.handler);
router.post("/doAddBylaw", handler_doAddBylaw.handler);
router.post("/doUpdateBylaw", handler_doUpdateBylaw.handler);
router.post("/doUpdateOffencesByBylaw", handler_doUpdateOffencesByBylaw.handler);
router.post("/doDeleteBylaw", handler_doDeleteBylaw.handler);
module.exports = router;
