"use strict";
const express_1 = require("express");
const handler_doGetAllLocations = require("../handlers/offences-post/doGetAllLocations");
const handler_doGetOffencesByLocation = require("../handlers/offences-post/doGetOffencesByLocation");
const handler_doGetAllOffences = require("../handlers/offences-post/doGetAllOffences");
const router = express_1.Router();
router.post("/doGetAllLocations", handler_doGetAllLocations.handler);
router.post("/doGetOffencesByLocation", handler_doGetOffencesByLocation.handler);
router.post("/doGetAllOffences", handler_doGetAllOffences.handler);
module.exports = router;
