"use strict";
const express_1 = require("express");
const handler_mtoExport = require("../handlers/plates-ontario-get/mtoExport");
const handler_mtoExportDownload = require("../handlers/plates-ontario-get/mtoExportDownload");
const handler_doGetPlatesAvailableForMTOLookup = require("../handlers/plates-ontario-post/doGetPlatesAvailableForMTOLookup");
const handler_mtoImport = require("../handlers/plates-ontario-get/mtoImport");
const handler_doMTOImportUpload = require("../handlers/plates-ontario-post/doMTOImportUpload");
const router = express_1.Router();
router.get("/mtoExport", handler_mtoExport.handler);
router.post("/doGetPlatesAvailableForMTOLookup", handler_doGetPlatesAvailableForMTOLookup.handler);
router.get("/mtoExport/:batchID", handler_mtoExportDownload.handler);
router.get("/mtoImport", handler_mtoImport.handler);
router.post("/doMTOImportUpload", handler_doMTOImportUpload.uploadHandler, handler_doMTOImportUpload.handler);
module.exports = router;
