"use strict";
const express_1 = require("express");
const permissionHandlers = require("../handlers/permissions");
const handler_mtoExport = require("../handlers/plates-ontario-get/mtoExport");
const handler_mtoExportDownload = require("../handlers/plates-ontario-get/mtoExportDownload");
const handler_doGetPlatesAvailableForMTOLookup = require("../handlers/plates-ontario-post/doGetPlatesAvailableForMTOLookup");
const handler_mtoImport = require("../handlers/plates-ontario-get/mtoImport");
const handler_doMTOImportUpload = require("../handlers/plates-ontario-post/doMTOImportUpload");
const router = express_1.Router();
router.get("/mtoExport", permissionHandlers.updateOrOperatorGetHandler, handler_mtoExport.handler);
router.post("/doGetPlatesAvailableForMTOLookup", permissionHandlers.updatePostHandler, handler_doGetPlatesAvailableForMTOLookup.handler);
router.get("/mtoExport/:batchID", permissionHandlers.updateOrOperatorGetHandler, handler_mtoExportDownload.handler);
router.get("/mtoImport", permissionHandlers.updateOrOperatorGetHandler, handler_mtoImport.handler);
router.post("/doMTOImportUpload", permissionHandlers.updateOrOperatorPostHandler, handler_doMTOImportUpload.uploadHandler, handler_doMTOImportUpload.handler);
module.exports = router;
