"use strict";
const express_1 = require("express");
const handler_convict = require("../handlers/tickets-ontario-get/convict");
const handler_convictDownload = require("../handlers/tickets-ontario-get/convictDownload");
const handler_doAddAllTicketsToConvictionBatch = require("../handlers/tickets-ontario-post/doAddAllTicketsToConvictionBatch");
const handler_doClearConvictionBatch = require("../handlers/tickets-ontario-post/doClearConvictionBatch");
const handler_doRemoveTicketFromConvictionBatch = require("../handlers/tickets-ontario-post/doRemoveTicketFromConvictionBatch");
const router = express_1.Router();
router.get("/convict", handler_convict.handler);
router.get("/convict/:batchID", handler_convictDownload.handler);
router.post("/doAddAllTicketsToConvictionBatch", handler_doAddAllTicketsToConvictionBatch.handler);
router.post("/doClearConvictionBatch", handler_doClearConvictionBatch.handler);
router.post("/doRemoveTicketFromConvictionBatch", handler_doRemoveTicketFromConvictionBatch.handler);
module.exports = router;
