"use strict";
const express_1 = require("express");
const permissionHandlers = require("../handlers/permissions");
const handler_convict = require("../handlers/tickets-ontario-get/convict");
const handler_convictDownload = require("../handlers/tickets-ontario-get/convictDownload");
const handler_doAddAllTicketsToConvictionBatch = require("../handlers/tickets-ontario-post/doAddAllTicketsToConvictionBatch");
const handler_doClearConvictionBatch = require("../handlers/tickets-ontario-post/doClearConvictionBatch");
const handler_doRemoveTicketFromConvictionBatch = require("../handlers/tickets-ontario-post/doRemoveTicketFromConvictionBatch");
const router = express_1.Router();
router.get("/convict", permissionHandlers.updateOrOperatorGetHandler, handler_convict.handler);
router.get("/convict/:batchID", permissionHandlers.updateOrOperatorGetHandler, handler_convictDownload.handler);
router.post("/doAddAllTicketsToConvictionBatch", permissionHandlers.updatePostHandler, handler_doAddAllTicketsToConvictionBatch.handler);
router.post("/doClearConvictionBatch", permissionHandlers.updatePostHandler, handler_doClearConvictionBatch.handler);
router.post("/doRemoveTicketFromConvictionBatch", permissionHandlers.updatePostHandler, handler_doRemoveTicketFromConvictionBatch.handler);
module.exports = router;
