import { Router } from "express";
import * as permissionHanders from "../handlers/permissions.js";
import handler_new from "../handlers/tickets-get/new.js";
import handler_view from "../handlers/tickets-get/view.js";
import handler_edit from "../handlers/tickets-get/edit.js";
import handler_byTicketNumber from "../handlers/tickets-get/byTicketNumber.js";
import handler_doGetTickets from "../handlers/tickets-post/doGetTickets.js";
import handler_doCreateTicket from "../handlers/tickets-post/doCreateTicket.js";
import handler_doUpdateTicket from "../handlers/tickets-post/doUpdateTicket.js";
import handler_doResolveTicket from "../handlers/tickets-post/doResolveTicket.js";
import handler_doUnresolveTicket from "../handlers/tickets-post/doUnresolveTicket.js";
import handler_doDeleteTicket from "../handlers/tickets-post/doDeleteTicket.js";
import handler_doRestoreTicket from "../handlers/tickets-post/doRestoreTicket.js";
import handler_doGetRemarks from "../handlers/tickets-post/doGetRemarks.js";
import handler_doAddRemark from "../handlers/tickets-post/doAddRemark.js";
import handler_doUpdateRemark from "../handlers/tickets-post/doUpdateRemark.js";
import handler_doDeleteRemark from "../handlers/tickets-post/doDeleteRemark.js";
import handler_doGetStatuses from "../handlers/tickets-post/doGetStatuses.js";
import handler_doAddStatus from "../handlers/tickets-post/doAddStatus.js";
import handler_doUpdateStatus from "../handlers/tickets-post/doUpdateStatus.js";
import handler_doDeleteStatus from "../handlers/tickets-post/doDeleteStatus.js";
import handler_reconcile from "../handlers/tickets-get/reconcile.js";
import handler_doAcknowledgeLookupError from "../handlers/tickets-post/doAcknowledgeLookupError.js";
import handler_doQuickReconcileMatches from "../handlers/tickets-post/doQuickReconcileMatches.js";
import handler_doReconcileAsMatch from "../handlers/tickets-post/doReconcileAsMatch.js";
import handler_doReconcileAsError from "../handlers/tickets-post/doReconcileAsError.js";
import handler_doGetRecentConvictionBatches from "../handlers/tickets-post/doGetRecentConvictionBatches.js";
import handler_doGetConvictionBatch from "../handlers/tickets-post/doGetConvictionBatch.js";
import handler_doCreateConvictionBatch from "../handlers/tickets-post/doCreateConvictionBatch.js";
import handler_doAddTicketToConvictionBatch from "../handlers/tickets-post/doAddTicketToConvictionBatch.js";
import handler_doLockConvictionBatch from "../handlers/tickets-post/doLockConvictionBatch.js";
import handler_doUnlockConvictionBatch from "../handlers/tickets-post/doUnlockConvictionBatch.js";
export const router = Router();
router.get("/", (_req, res) => {
    res.render("ticket-search", {
        headTitle: "Parking Tickets"
    });
});
router.post("/doGetTickets", handler_doGetTickets.handler);
router.get("/reconcile", permissionHanders.updateGetHandler, handler_reconcile.handler);
router.post("/doAcknowledgeLookupError", permissionHanders.updatePostHandler, handler_doAcknowledgeLookupError.handler);
router.post("/doReconcileAsMatch", permissionHanders.updatePostHandler, handler_doReconcileAsMatch.handler);
router.post("/doReconcileAsError", permissionHanders.updatePostHandler, handler_doReconcileAsError.handler);
router.post("/doQuickReconcileMatches", permissionHanders.updatePostHandler, handler_doQuickReconcileMatches.handler);
router.post("/doGetRecentConvictionBatches", permissionHanders.updateOrOperatorPostHandler, handler_doGetRecentConvictionBatches.handler);
router.post("/doGetConvictionBatch", permissionHanders.updateOrOperatorPostHandler, handler_doGetConvictionBatch.handler);
router.post("/doCreateConvictionBatch", permissionHanders.updatePostHandler, handler_doCreateConvictionBatch.handler);
router.post("/doAddTicketToConvictionBatch", permissionHanders.updatePostHandler, handler_doAddTicketToConvictionBatch.handler);
router.post("/doLockConvictionBatch", permissionHanders.updatePostHandler, handler_doLockConvictionBatch.handler);
router.post("/doUnlockConvictionBatch", permissionHanders.updatePostHandler, handler_doUnlockConvictionBatch.handler);
router.get(["/new", "/new/:ticketNumber"], permissionHanders.createGetHandler, handler_new.handler);
router.post("/doCreateTicket", permissionHanders.createPostHandler, handler_doCreateTicket.handler);
router.post("/doUpdateTicket", permissionHanders.createPostHandler, handler_doUpdateTicket.handler);
router.post("/doDeleteTicket", permissionHanders.createPostHandler, handler_doDeleteTicket.handler);
router.post("/doResolveTicket", permissionHanders.createPostHandler, handler_doResolveTicket.handler);
router.post("/doUnresolveTicket", permissionHanders.createPostHandler, handler_doUnresolveTicket.handler);
router.post("/doRestoreTicket", permissionHanders.updatePostHandler, handler_doRestoreTicket.handler);
router.post("/doGetRemarks", handler_doGetRemarks.handler);
router.post("/doAddRemark", permissionHanders.createPostHandler, handler_doAddRemark.handler);
router.post("/doUpdateRemark", permissionHanders.createPostHandler, handler_doUpdateRemark.handler);
router.post("/doDeleteRemark", permissionHanders.createPostHandler, handler_doDeleteRemark.handler);
router.post("/doGetStatuses", handler_doGetStatuses.handler);
router.post("/doAddStatus", permissionHanders.createPostHandler, handler_doAddStatus.handler);
router.post("/doUpdateStatus", permissionHanders.createPostHandler, handler_doUpdateStatus.handler);
router.post("/doDeleteStatus", permissionHanders.createPostHandler, handler_doDeleteStatus.handler);
router.get("/:ticketID", handler_view.handler);
router.get("/byTicketNumber/:ticketNumber", handler_byTicketNumber.handler);
router.get("/:ticketID/edit", permissionHanders.createGetHandler, handler_edit.handler);
export default router;
