"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteParkingTicketStatus = exports.updateParkingTicketStatus = exports.createParkingTicketStatus = exports.getParkingTicketStatuses = void 0;
const parkingDB_getParkingTicketStatuses = require("./getParkingTicketStatuses");
const parkingDB_createParkingTicketStatus = require("./createParkingTicketStatus");
const parkingDB_updateParkingTicketStatus = require("./updateParkingTicketStatus");
const parkingDB_deleteParkingTicketStatus = require("./deleteParkingTicketStatus");
exports.getParkingTicketStatuses = parkingDB_getParkingTicketStatuses.getParkingTicketStatuses;
exports.createParkingTicketStatus = parkingDB_createParkingTicketStatus.createParkingTicketStatus;
exports.updateParkingTicketStatus = parkingDB_updateParkingTicketStatus.updateParkingTicketStatus;
exports.deleteParkingTicketStatus = parkingDB_deleteParkingTicketStatus.deleteParkingTicketStatus;
