name: Coverage Testing (Pull)
on:
  pull_request:
jobs:
  Coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: browser-actions/setup-chrome@latest
      - name: Install Application
        run: |
          npm ci
          npm install -g mocha c8 cypress@10
      - name: Copy Test Config
        run: cp ./data/configTesting.js ./data/config.js
      - name: Run Coverage Testing
        run: c8 --reporter=lcov --reporter=text --reporter=text-summary mocha --timeout 10000 --exit
